USE master;
SET NOCOUNT ON;
IF DB_ID(N'DBA_Toolkit_Lab_Restore') IS NOT NULL
BEGIN ALTER DATABASE DBA_Toolkit_Lab_Restore SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE DBA_Toolkit_Lab_Restore; END;
IF DB_ID(N'DBA_Toolkit_Lab') IS NOT NULL
BEGIN ALTER DATABASE DBA_Toolkit_Lab SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE DBA_Toolkit_Lab; END;
IF SUSER_ID(N'DBA_Toolkit_TestLogin') IS NOT NULL DROP LOGIN DBA_Toolkit_TestLogin;
GO
